/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum18062026;

import javax.swing.JOptionPane;

/**
 *
 * @author Jaki
 */
public class FormNilai extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormNilai.class.getName());

    /**
     * Creates new form FormNilai
     */
    public FormNilai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        lblMatkul = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        txtMatkul = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTugas = new javax.swing.JTextField();
        txtUas = new javax.swing.JTextField();
        txtQuiz = new javax.swing.JTextField();
        txtUts = new javax.swing.JTextField();
        lblTugas = new javax.swing.JLabel();
        lblQuiz = new javax.swing.JLabel();
        lblUts = new javax.swing.JLabel();
        lblUas = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        lblNilai = new javax.swing.JLabel();
        lblProses = new javax.swing.JLabel();
        lblGrade = new javax.swing.JLabel();
        txtNilai = new javax.swing.JTextField();
        txtGrade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(0, 204, 204));
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("Form Penilaian Siswa");
        lblJudul.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNama.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNama.setText("Nama");

        lblKelas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblKelas.setText("Kelas");

        lblMatkul.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMatkul.setText("Mata Kuliah");

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtKelas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtKelas.addActionListener(this::txtKelasActionPerformed);

        txtMatkul.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtMatkul.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Input Nilai");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtTugas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTugas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtUas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtUas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtQuiz.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtQuiz.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtUts.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtUts.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lblTugas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTugas.setText("Tugas");

        lblQuiz.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQuiz.setText("Quiz");

        lblUts.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUts.setText("UTS");

        lblUas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUas.setText("UAS");

        btnProses.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnProses.setText("Proses");
        btnProses.addActionListener(this::btnProsesActionPerformed);

        lblNilai.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNilai.setText("Nilai");

        lblProses.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblProses.setForeground(new java.awt.Color(0, 204, 204));
        lblProses.setText("Hasil Proses");

        lblGrade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblGrade.setText("Grade");

        txtNilai.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtGrade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJudul)
                .addGap(335, 335, 335))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNama)
                            .addComponent(lblKelas)
                            .addComponent(lblMatkul))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txtKelas)
                            .addComponent(txtMatkul))
                        .addContainerGap(658, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTugas)
                            .addComponent(lblQuiz)
                            .addComponent(lblUts)
                            .addComponent(lblUas))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(269, 269, 269))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUas, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(txtQuiz)
                                    .addComponent(txtUts))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblProses))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNilai)
                                    .addComponent(lblGrade))
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblJudul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelas)
                    .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatkul)
                    .addComponent(txtMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnProses))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUas)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTugas, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblQuiz, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addComponent(txtUts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblUts, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProses)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNilai)
                                    .addComponent(txtNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGrade)
                                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(txtUas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(290, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelasActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        String nama = txtNama.getText();
        String kelas = txtKelas.getText();
        String matkul = txtMatkul.getText();
        
        if(nama.isEmpty()){
            JOptionPane.showMessageDialog(this, "Data Nama Tidak Boleh Kosong!");
            txtNama.requestFocus();
        }
        if(kelas.isEmpty()){
            JOptionPane.showMessageDialog(this, "Data Kelas Tidak Boleh Kosong!");
            txtKelas.requestFocus();
        }
        if(matkul.isEmpty()){
            JOptionPane.showMessageDialog(this, "Data Mata Kuliah Tidak Boleh Kosong!");
            txtMatkul.requestFocus();
        }
        
        if(txtQuiz.getText().isEmpty()||txtTugas.getText().isEmpty()||txtUts.getText().isEmpty()||txtUas.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nilai Harus di Inputkan!");
        }
        try{
        double quiz = validasiNilai(txtQuiz.getText(),"Quiz");
        double tugas = validasiNilai(txtTugas.getText(),"Tugas");
        double uts = validasiNilai(txtUts.getText(),"Uts");
        double uas = validasiNilai(txtUas.getText(),"Uas");
        
        double na = (0.15*quiz)+(0.2*tugas)+(0.3*uts)+(0.35*uas);
        txtNilai.setText(Double.toString(na));
        txtGrade.setText(KonversiNilai(na));
        
        JOptionPane.showMessageDialog(this, "\nNama : "+nama+" \nKelas : "+kelas+" \nMendapat nilai : "+na+" Atau setara dengan : "+KonversiNilai(na)+"\nUntuk Mata Kuliah : "+matkul,"Hasil Penilaian",JOptionPane.INFORMATION_MESSAGE);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Nilai harus berupa angka","Peringatan",JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(),"Pengecekan Nilai",JOptionPane.WARNING_MESSAGE);
        }
        finally{
            JOptionPane.showMessageDialog(this, "Pengecekan Selesai");
        }
    }//GEN-LAST:event_btnProsesActionPerformed
        private String KonversiNilai(double nilai){
            if(nilai>=80){
                return "A";
            }else if(nilai >=65){
                return "B";
            }else if(nilai >= 55){
                return "C";
            }else if(nilai >=40){
                return "D";
            }else{
                return "E";
            }
        }
        private Double validasiNilai(String input, String jenisNilai)throws Exception{
            double nilai = Double.parseDouble(input);
            if (nilai<0 || nilai>100){
                throw new Exception (jenisNilai+" Harus Antara 0-100");
            }return nilai;
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormNilai().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblMatkul;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNilai;
    private javax.swing.JLabel lblProses;
    private javax.swing.JLabel lblQuiz;
    private javax.swing.JLabel lblTugas;
    private javax.swing.JLabel lblUas;
    private javax.swing.JLabel lblUts;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtMatkul;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNilai;
    private javax.swing.JTextField txtQuiz;
    private javax.swing.JTextField txtTugas;
    private javax.swing.JTextField txtUas;
    private javax.swing.JTextField txtUts;
    // End of variables declaration//GEN-END:variables
}
